name: Questions  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
          
      - name: /questions get lambda deploy zip
        uses: postman-open-technologies/questions@main
        with:
            args: zip -qq -r m-s-questions-g.zip questions/get/index.js node_modules
      - name: question get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-questions-g
            zip_file: m-s-questions-g.zip
      - name: /questions post lambda deploy zip
        uses: postman-open-technologies/questions@main
        with:
            args: zip -qq -r m-s-questions-po.zip questions/post/index.js node_modules
      - name: question get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-questions-po
            zip_file: m-s-questions-po.zip
      - name: /questions/{question_id} get lambda deploy zip
        uses: postman-open-technologies/questions@main
        with:
            args: zip -qq -r m-s-questions-question-g.zip questions/question_id/get/index.js node_modules
      - name: question get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-questions-question-g
            zip_file: m-s-questions-question-g.zip
      - name: /questions/{question_id} put lambda deploy zip
        uses: postman-open-technologies/questions@main
        with:
            args: zip -qq -r m-s-questions-question-pu.zip questions/question_id/put/index.js node_modules
      - name: question get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-questions-question-pu
            zip_file: m-s-questions-question-pu.zip
      - name: /questions/{question_id} delete lambda deploy zip
        uses: postman-open-technologies/questions@main
        with:
            args: zip -qq -r m-s-questions-question-d.zip questions/question_id/delete/index.js node_modules
      - name: question get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-questions-question-d
            zip_file: m-s-questions-question-d.zip          